name: Test_Move_Prover

on:
  pull_request:
    types: [opened, reopened, synchronize]
  # repository_dispatch:
  #   types: [new_PR]

jobs:
  install_and_test_Move_Prover:

    runs-on: ubuntu-latest

    steps:
    - name: Install Z3
      uses: pavpanchekha/setup-z3@v1.2
    - name: Install .NET Core SDK and Boogie 1
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - name: Install .NET Core SDK and Boogie 2
      run: |
        sudo dpkg -i --no packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install apt-transport-https
        sudo apt-get update
        sudo apt-get install dotnet-sdk-3.1
        dotnet tool install --global Boogie
    - name: Export the environment variables
      run: |
        echo "::set-env name=BOOGIE_EXE::/home/runner/.dotnet/tools/boogie"
        echo "::set-env name=Z3_EXE::`which z3`"
    - name: Checkout libra
      uses: actions/checkout@v2
      with:
        path: "libra"
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked libra/libra
        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
    - name: Build move-prover
      working-directory: ./libra/language/move-prover/bytecode-to-boogie
      run: cargo build
    - name: Test move-prover
      working-directory: ./libra/language/move-prover/bytecode-to-boogie
      timeout-minutes: 30 # normally, expected to be done within 10 mins.
      run: cargo test
