name: Test_Move_Prover

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  install_and_test_Move_Prover:

    runs-on: ubuntu-latest

    steps:
    - name: Install Z3
      uses: pavpanchekha/setup-z3@v1.2

    - name: Install .NET Core SDK
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https
        sudo apt-get update
        sudo apt-get install dotnet-sdk-3.1

    - name: Install Boogie
      run: |
        dotnet tool install --global Boogie

    - name: Export the environment variables for Z3 and Boogie
      run: |
        echo "::set-env name=Z3_EXE::`which z3`"
        echo "::set-env name=BOOGIE_EXE::`which boogie`"

    - name: Echo the environment variables
      run: |
        echo $Z3_EXE
        echo $BOOGIE_EXE
        which z3
        which boogie

    - name: Checkout libra
      uses: actions/checkout@v2
      with:
        path: 'libra'


    - name: Test move-prover
      working-directory: ./libra/language/move-prover/bytecode-to-boogie
      run: cargo test
